### ISSUE TITLE
Adaptation

### ISSUE THREAD

**Issue by jongfeel** [jongfeel/TaleOfKim#1]
각색 내용
- 허생 => 김씨, 컴퓨터와 소프트웨어의 기본에 충실한 인물
- 컴퓨터를 이해하고 소프트웨어를 만든다는게 코딩을 잘하면 되는게 아니라는 걸 관통하는 주제

시대적 배경
- 현대 개발자의 시대적 배경으로 변경
- 많은 부분에서 안맞는게 생길텐데, 그래도 잘 각색해봐야 할 듯

캐릭터 분석
- 허생의 아내
  - 지금은 결혼을 안하는 사람도 많고, 결혼 한다 해도 일찍 하지는 않음
  - 그러면??? 그냥 동거하는 여친으로 해보는건 어떨까?
- 변씨의 경우
  - 원문도 투자자였으니, 현대에도 투자자로 두는게 좋을 듯
- 이완
  - 원문은 어영대장이고 그게 시대 상황과 맞물려 있어서 마땅한 캐릭터로 변신 시키기가 어려움
  - 어쨌든 나라의 일을 해야 하고 장관 쯤으로 하는게 맞을텐데 개발 관련된 것이어야 하니 과학기술정보통신부 장관으로 하면 내용이 세금 낭비하는 삽질하는 사업 쪽으로 빠질 듯 하니 아예 다른 인물로 각색하는게 좋을 듯 - 어렵다

상황의 각색
- 묵적골? 판교 정도로 하면 좋을 듯

**Comment by jongfeel** [comment]
여친과의 동거는 대한민국 정서상 공격이 들어올 가능성이 있으므로

시대상을 반영해 직업이 있는 공무원으로 해서
김씨에 의존적인 인물이 아닌 자립성 있는 여성으로 해보면 좋을 듯

다만 김씨의 태도에 조금 불만이 있고 더 잘될 수 있는데 안하고 있는 태도에 불만을 가지는 성격으로 세팅하면 자연스럽게 될 것 같다.

**Comment by jongfeel** [comment]
변씨의 경우 투자자로 하면 사업 얘기로 빠져야 하기 때문에 소프트웨어쪽과 크게 상관이 없는 일이 될 수가 있다.

그래서...

온라인 상으로는 아는 사이인데 한번도 만난적도 없고 얘기한 적도 없는 사이로 설정해 두고
어느 대기업의 CTO 정도로 설정해 두면 사업이 아니라 기술적인 이야기로 자연스럽게 흘러가게 될 것이다.

**Comment by yoonucho** [comment]
멘토님 흥미진진하네요 ㅋ 카카오페이라니 ㅋ

**Comment by jongfeel** [comment]
@yoonucho 

네 이게 디테일이 살아 있는게 갑자기 현금을 준비한다고 해도
사과박스 2개에 눌러 담아야 하고
1억원 이상을 한번에 이체해 보셨는지 모르겠지만
일 이체 최대 한도도 정해져 있기 때문에 한번에 이체를 못하죠.

뭐 어쨌건 옛날 얘기를 현대적인 시각과 현실성으로 고려해서 이렇게 만든 건데
재미있게 보셨다면 감사합니다.
